#!/usr/bin/python -tt

from string import Template
from optparse import OptionParser, OptionValueError
from urlparse import urljoin
from sys import argv
import os

class BuildKs(object):
	"""
	Class BuildKS: Constructs a kickstart file based on premade template
	"""
	
	def __init__(self):
		"""
		Builds the parser menu, sets attibutes
		"""

		# Attributes
		self.template_file = 'ks_template.tmpl'	
		self.base_url = 'http://rhn.missouri.edu/pub'
		self.repo_name = 'csgrepo'
		self.repo_url = '/'.join([self.base_url,self.repo_name])
		self.valid_release = [4, 5, 6]
		self.valid_arch = ['x86_64', 'i386']
		# args_required should be set to minimum required arguments
		self.args_required = 5

		# Parser options
		parser = OptionParser(
			add_help_option=True,
			usage = "%prog [options] <hostname> <ipaddress> <netmask> <gateway> <nameserver>",
			version = "%prog 1.0",
		)

		# These options are set by default
		parser.set_defaults(
			arch = 'x86_64',
			release = '5',
			bootstrap = 'bootstrap.sh',
		)

		parser.add_option('-r', '--release', action='callback',type='string', dest='release',
						 help='Distribution Release, (i.e., 5 or 6)', callback=self.release_callback)
		parser.add_option('-a', '--arch', action='callback', type='string', dest='arch',
						 help='x86_64 or i386', callback=self.arch_callback)
		parser.add_option('-b', '--bootstrap', action='store', type='string', dest='bootstrap',
						 help='Your bootstrap script (i.e., bakerlu_bootstrap.sh)')
	
		# Set options and args
		(self.options, self.args) = parser.parse_args()

		# Error out if args are less than self.args_required
		if len(self.args) < self.args_required:
			parser.error("Incorrect number of arguments")

	def release_callback(self, option, opt_str, value, parser):
		"""
		Callback to verify that a valid release number was specified
		"""

		if parser.values.release not in self.valid_release:
			raise OptionValueError("Not a valid release number, try 5 or 6")

	def arch_callback(self, option, opt_str, value, parser):
		"""
		Callback to verify that arch is valid
		"""

		if parser.values.arch not in self.valid_arch:
			raise OptionValueError("Not a valid arch, try x86_64 or i386")

	def build_url_segments(self):
		"""
		Construct a url segment to match the installation directory on rhn
		ie, rhn.missouri.edu/pub/RHEL5_64
		"""
		
		# Build the installation directory
		install_dir = []
		install_dir.append('RHEL'+self.options.release)

		if self.options.arch == 'x86_64':
			install_dir.append('64')
		else:
			install_dir.append('i386')
	
		# Create the install URL segment
		install_segment = '_'.join(install_dir)

		# Build the repo URL segment
		if self.options.arch != 4:
			repo_segment = '/'.join([self.options.release+'Server', self.options.arch])
		else:
			repo_segment = '/'.join([self.options.release, self.options.arch])

		results = {
			'install_segment': install_segment,
			'repo_segment': repo_segment,
		}

		return results

	def build(self, output_dir):
		"""
		Constructs template based on the file self.template_file
		"""

		try:
			f = open(self.template_file, 'r')
			try:
				lines = f.read()
			finally:
				f.close()
		except IOError, e:
			print "Problem reading file: %s" % e

		# Create template from the file
		tmpl = Template(lines)

		# Call install_dir() to build our url segment
		url_segments = self.build_url_segments()

		# Substitute template variables with arguments
		output = tmpl.safe_substitute(
			install_url = '/'.join([self.base_url, url_segments.get('install_segment')]),
			hostname = self.args[0],
			ip = self.args[1],
			netmask = self.args[2],
			gateway = self.args[3],
			dns = self.args[4],
			bootstrap = self.options.bootstrap,
			repo_url = '/'.join([self.repo_url, url_segments.get('repo_segment')]),	
		)

		dir = os.path.dirname(output_dir)
		# The kickstart filename is <hostname>.ks
		filename = '.'.join([self.args[0], 'ks'])
		file = os.path.join(dir, filename)

		if os.path.exists(dir):			
			try:
				f = open(file, 'w')
				try:
					f.write(output)
				finally:
					f.close()
			except IOError, e:
				print "Problem reading file: %s" % e
		else:
			raise DirectoryError('Directory does not exist')

def main():
	output_dir = '/var/www/html/pub/ks/'
	ks = BuildKs()
	ks.build(output_dir)

if __name__ == '__main__':
	main()
