#!/usr/bin/python -tt

from kickstartbuild import KickstartBuild

def main():
	#output_dir = '/var/www/html/pub/ks/'
	output_dir = '/home/ljb6tw/'
	ks = KickstartBuild()
	ks.check_args()
	ks.validate()
	ks.build(output_dir)

if __name__ == '__main__':
	main()
